name: "Build OCP addons"
description: "Use the build environment to also build OCP Addons (https://github.com/jdegenstein/ocp-addons)"
inputs:
  os:
    description: "Operating system to use for the build"
    required: true
  python-version:
    description: "Python version to use for the build"
    required: true
  sed-i:
    description: "Sed in-place command for the OS"
    required: true
  github-token:
    required: true
    description: 'GitHub Token'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    # - - -

    - name: (Linux) Install ca-certificates
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        # (Linux) Install ca-certificates
        set -e
        set -u
        set -o pipefail

        apt-get update -qq  
        DEBIAN_FRONTEND=noninteractive apt-get install -qq ca-certificates > /dev/null 2>&1

    # - - -
    
    - name: Set up Python ${{ inputs.python-version }} via micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment-ocpaddons-${{ inputs.python-version }}.yml
        log-level: warning
        init-shell: bash
        cache-downloads: true
        cache-environment: true
        cache-environment-key: environment-ocpaddons-${{ inputs.python-version }}-${{ inputs.os }}-novtk

    # - - -

    - name: Install Linux Dependencies (x86_64)
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        # Install Linux Dependencies (x86_64)
        set -e
        set -o pipefail

        apt-get update -qq
        apt-get install -qq -y freetype* libfreetype6-dev libgl1-mesa-glx  git \
                               patch gcc g++ build-essential  > /dev/null 2>&1

        pip install auditwheel patchelf build wheel
        micromamba info
        micromamba list

    # - - -

    - name: Install MacOS Dependencies (x86_64 / arm64)
      if: runner.os == 'macOS'
      shell: bash -l {0}
      run: |
        # Install MacOS Dependencies (x86_64 / arm64)
        set -e
        set -o pipefail
        
        brew install automake gsed

        pip install delocate build wheel

        # curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
        # sudo tar -xf MacOSX11.3.sdk.tar.xz -C /opt

    # - - -

    - name: Install Windows Dependencies (x86_64)
      if: runner.os == 'Windows'
      shell: bash -l {0}
      run: |
        # Install Windows Dependencies (x86_64)
        set -e
        set -o pipefail
        
        micromamba install vs2019_win-64 -c conda-forge
        pip install delvewheel build wheel

    # - - -
    
    - name: Download OCCT SDK
      uses: actions/download-artifact@v4
      with:
        name: SDK_${{ inputs.os }}-py_${{ inputs.python-version }}-novtk
        run-id: ${{ env.SDK_RUNID }}
        github-token: ${{ inputs.github-token }}

    # - - -

    - name: Clone ocp-addons and build wheel 
      shell: bash -l {0}
      run: |
        # Clone ocp-addons and build wheel 
        set -e
        set -o pipefail

        git clone https://github.com/jdegenstein/ocp-addons.git
        
        cd ocp-addons
        git switch ocp-build-system
        
        # if [[ "$RUNNER_OS" == "macOS" ]]; then
        #   export CC=clang
        #   export CXX=clang++
          
        #   clang++ --version

        # elif [[ "$RUNNER_OS" == "Linux" ]]; then

        #   export CC=/usr/bin/gcc
        #   export CXX=/usr/bin/g++
        #   g++ --version
        # fi

        export OCCT_SDK="$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk"
        python -m build -n -w
        ls -l dist

    # - - -

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: ocp-addons-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}-orig
        path: ocp-addons/dist/*.whl

    # - - -

    - name: Repair Linux Wheel (x86_64)
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        # Repair Linux Wheel (x86_64)

        set -e
        set -o pipefail
        
        cd ocp-addons
        VERSION=$(awk -F'"' '/^__version__/ {print $2}' setup.py)

        # ls -l build/lib.linux*/*.so
        # objdump -T build/lib.linux*/*.so | grep GLIBC_ | sed 's/.*GLIBC_\\([.0-9]*\\).*/\\1/g' | sort -Vu

        env LD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/lib auditwheel repair \
            --plat manylinux_2_31_x86_64 dist/ocp_addons-${VERSION}*.whl

    # - - -

    - name: Repair MacOS Wheel (x86_64 / arm64)
      if: runner.os == 'macOS'
      shell: bash -l {0}
      run: |
        # Repair MacOS Wheel (x86_64 / arm64)

        set -e
        set -o pipefail
        
        cd ocp-addons
        VERSION=$(awk -F'"' '/^__version__/ {print $2}' setup.py)

        # Patch @rpath/libc++.1.dylib to /usr/lib/libc++.1.dylib
        cd dist
        python -m wheel unpack ocp_addons-${VERSION}*.whl
        rm ocp_addons-${VERSION}*.whl
        # install_name_tool -change @rpath/libc++.1.dylib /usr/lib/libc++.1.dylib ocp_addons*/*.so
        install_name_tool -add_rpath /usr/lib ocp_addons*/*.so
        for lib in ocp_addons.dylibs/libTK*.dylib; do
          install_name_tool -add_rpath /usr/lib  $lib
        done
        python -m wheel pack ocp_addons-${VERSION}
        cd ..
               
        # @rpath/libc++.1.dylib confuses delocate but can safely be ignored
        DYLD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/lib:/usr/lib python \
            -m delocate.cmd.delocate_wheel \
            --ignore-missing-dependencies \
            --wheel-dir=wheelhouse dist/ocp_addons-${VERSION}*.whl

    # - - -

    - name: Repair Windows Wheel (x86_64) 
      if: runner.os == 'Windows'
      shell: bash -l {0}
      run: |
        # Repair Windows Wheel (x86_64)
        set -e
        set -o pipefail
        
        cd ocp-addons
        VERSION=$(awk -F'"' '/^__version__/ {print $2}' setup.py)

        PATH=LD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/lib:$PATH
        python -m delvewheel repair --wheel-dir=wheelhouse dist/ocp_addons-${VERSION}*.whl

    # - - -

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocp-addons-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}
        path: ocp-addons/wheelhouse/*.whl

    # - - -

    - name: Download vtk cadquery_ocp wheel
      uses: actions/download-artifact@v4
      with:
        name: cadquery-ocp-vtk-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}
        run-id: ${{ env.SDK_RUNID }}
        github-token: ${{ inputs.github-token }}

    # - - -

    - name: Install OCP wheel
      shell: bash -l {0}
      run: |
        # Install VTK and OCP wheel
        set -e
        set -o pipefail
        

    # - - -

    - name: Test Repaired Wheel and Run Package Tests
      shell: bash -l {0}
      run: |
        # Test Repaired Wheel and Run Package Tests
        set -e
        set -o pipefail
        
        pip install *.whl
        python -c "import OCP; print('Success: OCP', OCP.__version__)"

        git clone https://github.com/snoyer/ocpsvg.git
        cd ocpsvg
        ${{ inputs.sed-i }} 's/cadquery-ocp >= 7\.8\.1, < 7\.9\.0/cadquery-ocp >= 7.8, < 8.0/g' pyproject.toml
        pip install .
        cd ..

        git clone https://github.com/gumyr/build123d.git
        cd build123d 
        git checkout 1af4b0c3129dd152a1c9cb01400c1e648a5de8e2  # pre Gordon face to avoid 7.9. issues
        ${{ inputs.sed-i }} 's/cadquery-ocp >= 7\.8, < 7\.9/cadquery-ocp >= 7.8, < 8.0/g' pyproject.toml
        pip install .
        cd ..

        # micromamba deactivate
        # micromamba create --name ocpaddonstest python=${{ inputs.python-version }} --file env.yml --yes
        # micromamba activate ocpaddonstest
        # micromamba info --envs

        pip install ocp-addons/wheelhouse/ocp_addons*.whl
        python -c "import ocp_addons;print('ocp_addons imported successfully')"
        
        pip list
        command -v python
        python ocp-addons/test.py

