name: "Build OCP addons"
description: "Use the build environment to also build OCP Addons (https://github.com/jdegenstein/ocp-addons)"
inputs:
  os:
    description: "Operating system to use for the build"
    required: true
  python-version:
    description: "Python version to use for the build"
    required: true
  sed-i:
    description: "Sed in-place command for the OS"
    required: true
  use-vtk:
    description: "Whether to use VTK in the build"
    required: true
  github-token:
    required: true
    description: 'GitHub Token'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    # - - -

    - name: (Linux) Install ca-certificates
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        # (Linux) Install ca-certificates
        set -e
        set -u
        set -o pipefail

        apt-get update -qq  
        DEBIAN_FRONTEND=noninteractive apt-get install -qq ca-certificates > /dev/null 2>&1

    # - - -
    
    - name: Set up Python ${{ inputs.python-version }} via micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment-${{ inputs.python-version }}.yml
        log-level: warning
        init-shell: bash
        cache-downloads: true
        cache-environment: true
        cache-environment-key: environment-${{ inputs.python-version }}-${{ inputs.os }}-${{ inputs.use-vtk }}

    # - - -

    - name: Install Linux Dependencies (x86_64)
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        # Install Linux Dependencies (x86_64)
        set -e
        set -o pipefail

        apt-get update -qq
        apt-get install -qq -y freetype* libfreetype6-dev libgl1-mesa-glx  git \
                                patch clang build-essential> /dev/null 2>&1


        micromamba install -c conda-forge gxx_linux-64=12
        pip install auditwheel patchelf build wheel
        micromamba info
        micromamba list

    # - - -

    - name: Install MacOS Dependencies (x86_64 / arm64)
      if: runner.os == 'macOS'
      shell: bash -l {0}
      run: |
        # Install MacOS Dependencies (x86_64 / arm64)
        set -e
        set -o pipefail
        
        brew install automake gsed

        pip install delocate build wheel

        # curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
        # sudo tar -xf MacOSX11.3.sdk.tar.xz -C /opt

    # - - -

    - name: Install Windows Dependencies (x86_64)
      if: runner.os == 'Windows'
      shell: bash -l {0}
      run: |
        # Install Windows Dependencies (x86_64)
        set -e
        set -o pipefail
        
        micromamba install vs2019_win-64 -c conda-forge
        pip install delvewheel build wheel

    # - - -
    
    - name: Download OCCT and VTK SDK
      uses: actions/download-artifact@v4
      with:
        name: SDK_${{ inputs.os }}-py_${{ inputs.python-version }}-${{ inputs.use-vtk }}
        run-id: ${{ env.SDK_RUNID }}
        github-token: ${{ inputs.github-token }}

    # - - -
    
    # - name: Download vtk cadquery_ocp wheel
    #   if: inputs.use-vtk == 'vtk'
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: cadquery-ocp-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}
    #     run-id: ${{ env.SDK_RUNID }}
    #     github-token: ${{ inputs.github-token }}

    # - - -

    - name: Clone ocp-addons
      shell: bash -l {0}
      run: |
        # Clone ocp-addons
        set -e
        set -o pipefail

        git clone https://github.com/jdegenstein/ocp-addons.git

        cd ocp-addons

        ${{ inputs.sed-i }} '/include_dirs=\[/a\    os.path.join(os.environ["GITHUB_WORKSPACE"], "occt-7.9.1-${{ inputs.use-vtk }}", "include", "opencascade"),' setup.py
        ${{ inputs.sed-i }} '/library_dirs=\[/a\    os.path.join(os.environ["GITHUB_WORKSPACE"], "occt-7.9.1-${{ inputs.use-vtk }}", "lib"),' setup.py
        
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          ${{ inputs.sed-i }} 's/\(extra_compile_args=\["-O3"\)\(.*\)/\1, "-D_GLIBCXX_USE_CXX11_ABI=0", "-std=c++17"\2/' setup.py
        fi

        cat setup.py

        # ls -l $GITHUB_WORKSPACE/occt-7.9.1-${{ inputs.use-vtk }}/
        # ls -l $GITHUB_WORKSPACE/occt-7.9.1-${{ inputs.use-vtk }}/include/opencascade
        # ls -l $GITHUB_WORKSPACE/occt-7.9.1-${{ inputs.use-vtk }}/lib

    # - - -

    - name: Build Wheel 
      shell: bash -l {0}
      run: |
        # Build Wheel 

        cd ocp-addons

        # if [[ "$RUNNER_OS" == "macOS" ]]; then
        #   export SDKROOT=/opt/MacOSX11.3.sdk

        #   export CFLAGS="-isysroot $SDKROOT $CFLAGS"
        #   export CXXFLAGS="-isysroot $SDKROOT $CXXFLAGS"
        #   export LDFLAGS="-isysroot $SDKROOT $LDFLAGS"
        # fi

        python -m build -n

    # - - -

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: ocp-addons-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}
        path: ocp-addons/dist/*.whl

    # - - -

    - name: Repair Linux Wheel (x86_64)
      if: runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        # Repair Linux Wheel (x86_64)

        set -e
        set -o pipefail
        
        cd ocp-addons

        # ls -l build/lib.linux*/*.so
        # objdump -T build/lib.linux*/*.so | grep GLIBC_ | sed 's/.*GLIBC_\\([.0-9]*\\).*/\\1/g' | sort -Vu

        env LD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-7.9.1-${{ inputs.use-vtk }}/lib auditwheel repair --plat manylinux_2_31_x86_64 dist/ocp_addons-*.whl

    # - - -

    - name: Repair MacOS Wheel (x86_64 / arm64)
      if: runner.os == 'macOS'
      shell: bash -l {0}
      run: |
        # Repair MacOS Wheel (x86_64 / arm64)

        set -e
        set -o pipefail
        
        cd ocp-addons

        # Patch @rpath/libc++.1.dylib to /usr/lib/libc++.1.dylib
        cd dist
        python -m wheel unpack ocp_addons-*.whl
        rm ocp_addons-*.whl
        install_name_tool -change @rpath/libc++.1.dylib /usr/lib/libc++.1.dylib ocp_addons*/*.so
        otool -L ocp_addons*/*.so
        python -m wheel pack ocp_addons-*
        cd ..

        DYLD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-7.9.1-${{ inputs.use-vtk }}/lib:/usr/lib python -m delocate.cmd.delocate_wheel --wheel-dir=wheelhouse dist/ocp_addons*.whl

    # - - -

    - name: Repair Windows Wheel (x86_64) 
      if: runner.os == 'Windows'
      shell: bash -l {0}
      run: |
        # Repair Windows Wheel (x86_64)
        set -e
        set -o pipefail
        
        cd ocp-addons
        
        PATH=LD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-7.9.1-${{ inputs.use-vtk }}/lib:$PATH
        python -m delvewheel repair --wheel-dir=wheelhouse dist/ocp_addons*.whl

    # - - -

    - name: Download novtk cadquery_ocp wheel
      if: inputs.use-vtk == 'novtk'
      uses: actions/download-artifact@v4
      with:
        name: cadquery-ocp-novtk-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}
        run-id: ${{ env.SDK_RUNID }}
        github-token: ${{ inputs.github-token }}

    # - - -

    - name: Install VTK and OCP wheel
      shell: bash -l {0}
      run: |
        # Install VTK and OCP wheel
        set -e
        set -o pipefail
        
        if [[ "${{ inputs.use-vtk }}" == "vtk" ]]; then
          pip install vtk==${{ env.VTK }}
        fi
        ls -l
        pip install *.whl

        python -c "import OCP; print('Success: OCP', OCP.__version__)"

    # - - -

    - name: Test Repaired Wheel and Run Package Tests
      shell: bash -l {0}
      run: |
        # Test Repaired Wheel and Run Package Tests
        set -e
        set -o pipefail
        
        micromamba deactivate
        micromamba create --name ocpaddonstest python=${{ inputs.python-version }} --file env.yml --yes
        micromamba activate ocpaddonstest
        micromamba info --envs
        ls wheelhouse/*
        pip install wheelhouse/ocp_addons*.whl
        micromamba list
        python -c "import ocp_addons;print('ocp_addons imported successfully')"
        python test.py

    # - - -

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocp_addons-${{ inputs.os }}-cp${{ inputs.python-version }}
        path: wheelhouse/*.whl
