name: "Build OCP addons"
description: "Use the build environment to also build OCP Addons (https://github.com/jdegenstein/ocp-addons)"
inputs:
  os:
    description: "Operating system to use for the build"
    required: true
  python-version:
    description: "Python version to use for the build"
    required: true
  shells:
    description: "Shell configuration for the OS"
    required: true
  github-token:
    required: true
    description: 'GitHub Token'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    # - - -

    - name: Install Linux Dependencies (x86_64)
      if: runner.os == 'Linux'
      shell: bash -leo pipefail {0}
      run: |
        # Install Linux Dependencies (x86_64)

        apt-get update -qq
        apt-get install -qq -y freetype* libfreetype6-dev libgl1-mesa-glx git \
                               ca-certificates patch gcc g++ build-essential  > /dev/null 2>&1

    # - - -

    - name: Install MacOS Dependencies (x86_64 / arm64)
      if: runner.os == 'macOS'
      shell: bash -leo pipefail {0}
      run: |
        # Install MacOS Dependencies (x86_64 / arm64)

        brew install gsed
        # ensure gnu sed is in PATH before system (BSD) sed
        cat <<EOF > $GITHUB_PATH
        $GITHUB_PATH
        $(brew --prefix gnu-sed)/libexec/gnubin"
        EOF

    # - - -
    
    - name: Prepare environment.yml
      shell: bash -leo pipefail {0}
      run: |
        # Install Linux Dependencies (x86_64)

        echo "1 ======"
        cat $GITHUB_PATH
        echo "2 ======"
        echo $PATH
        echo "3 ======"
        ls "$(brew --prefix gnu-sed)/libexec/gnubin"
        echo "4 ======"
        command -v sed

        sed -i 's/__PY_VERSION__/${{ inputs.python-version }}/' environment-ocpaddons.yml

        cat environment-ocpaddons.yml

    # - - -
    
    - name: Set up Python ${{ inputs.python-version }} via micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment-ocpaddons.yml
        log-level: warning
        init-shell: ${{ inputs.shells }}
        cache-environment: true
        cache-environment-key: environment-ocpaddons-${{ inputs.python-version }}-${{ inputs.os }}-novtk

    # - - -
    
    - name: Download OCCT SDK
      uses: actions/download-artifact@v4
      with:
        name: SDK_${{ inputs.os }}-py_${{ inputs.python-version }}-novtk
        run-id: ${{ env.SDK_RUNID }}
        github-token: ${{ inputs.github-token }}

    # - - -

    - name: Clone ocp-addons and build wheel 
      if: runner.os != 'Windows'
      shell: bash -leo pipefail {0}
      env:
        OCCT_SDK: ${{ github.workspace }}/occt-${{ env.OCCT }}-novtk  
      run: |
        # Clone ocp-addons and build wheel 

        git clone https://github.com/jdegenstein/ocp-addons.git
        cd ocp-addons
        git switch ocp-build-system
        
        python -m build -n -w
        ls -l dist

    # - - -

    - name: Clone ocp-addons and build wheel 
      if: runner.os == 'Windows'
      shell: cmd
      env:
        OCCT_SDK: ${{ github.workspace }}\occt-${{ env.OCCT }}-novtk      
      run: |
        rem Clone ocp-addons and build wheel 
        
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set CC=cl.exe
        set CXX=cl.exe

        git clone https://github.com/jdegenstein/ocp-addons.git
        cd ocp-addons
        git switch ocp-build-system

        micromamba run -n build-ocp python -m build -n -w
        dir dist

    # - - -

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: ocp-addons-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}-orig
        path: ocp-addons/dist/*.whl

    # - - -

    - name: Repair Linux Wheel (x86_64)
      if: runner.os == 'Linux'
      shell: bash -leo pipefail {0}
      run: |
        # Repair Linux Wheel (x86_64)
        
        pip install auditwheel patchelf

        cd ocp-addons
        VERSION=$(python setup.py --version)

        LD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/lib auditwheel repair \
            --plat manylinux_2_31_x86_64 dist/ocp_addons-${VERSION}*.whl

    # - - -

    - name: Repair MacOS Wheel (x86_64 / arm64)
      if: runner.os == 'macOS'
      shell: bash -leo pipefail {0}
      run: |
        # Repair MacOS Wheel (x86_64 / arm64)
        
        pip install delocate

        cd ocp-addons
        VERSION=$(python setup.py --version)

        # Patch @rpath/libc++.1.dylib to /usr/lib/libc++.1.dylib to ensure delocate works successfully
        cd dist
        python -m wheel unpack ocp_addons-${VERSION}*.whl
        
        rm ocp_addons-${VERSION}*.whl
        
        install_name_tool -change @rpath/libc++.1.dylib /usr/lib/libc++.1.dylib ocp_addons*/*.so
        
        for lib in "$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/lib"/libTK*.dylib; do
          install_name_tool -change @rpath/libc++.1.dylib /usr/lib/libc++.1.dylib $lib
        done
        
        python -m wheel pack ocp_addons-${VERSION}
        cd ..
               
        DYLD_LIBRARY_PATH=$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/lib:/usr/lib python \
            -m delocate.cmd.delocate_wheel \
            --ignore-missing-dependencies \
            --wheel-dir=wheelhouse dist/ocp_addons-${VERSION}*.whl

    # - - -

    - name: Repair Windows Wheel (x86_64) 
      if: runner.os == 'Windows'
      shell: bash -leo pipefail {0}
      run: |
        # Repair Windows Wheel (x86_64)

        pip install delvewheel

        cd ocp-addons
        VERSION=$(python setup.py --version)

        ls -l $GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/win64/vc14/bin

        PATH=$GITHUB_WORKSPACE/occt-${{ env.OCCT }}-novtk/win64/vc14/bin:$PATH python -m delvewheel repair --wheel-dir=wheelhouse dist/ocp_addons-${VERSION}*.whl

    # - - -

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocp-addons-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}
        path: ocp-addons/wheelhouse/*.whl



