name: "Test OCP"
description: "Testing OCP wheels with build123d and CadQuery"
inputs:
  os:
    description: "Operating system to use for the build"
    required: true
  python-version:
    description: "Python version to use for the build"
    required: true
  use-vtk:
    description: "Whether to use VTK in the build"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    # - - -

    - name: (Linux) Install ca-certificates
      if: env.PYWRAP == 'true' && runner.os == 'Linux'
      shell: bash -l {0}
      run: |
        # (Linux) Install ca-certificates
        set -e
        set -u
        set -o pipefail

        sudo apt-get update -qq  
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq ca-certificates > /dev/null 2>&1

    # - - -

    - name: (All) Patch environment.yml for Python
      shell: bash -l {0}
      run: |
        sed -i.bak 's/python=3.13/python=${{ inputs.python-version }}/' environment.yml

    - name: Set up Python ${{ inputs.python-version }} via micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        log-level: warning
        init-shell: ${{ inputs.shells }}
        cache-downloads: true
        cache-environment: true
        cache-environment-key: environment-${{ inputs.python-version }}-${{ inputs.os }}-${{ inputs.use-vtk }}

    # - - -

    - name: Create the test environment
      shell: bash -l {0}
      run: |
        # Create the test environment
        set -e
        set -o pipefail

        micromamba create -y -n test python=${{ inputs.python-version }}
        micromamba activate test
        pip install pytest docutils ipython

    # - - -
    
    - name: Download vtk cadquery_ocp wheel
      if: inputs.use-vtk == 'vtk'
      uses: actions/download-artifact@v4
      with:
        name: cadquery-ocp-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}

    # - - -

    - name: Download novtk cadquery_ocp wheel
      if: inputs.use-vtk == 'novtk'
      uses: actions/download-artifact@v4
      with:
        name: cadquery-ocp-novtk-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}

    # - - -

    - name: Install VTK and OCP wheel
      shell: bash -l {0}
      run: |
        # Install VTK and OCP wheel
        set -e
        set -o pipefail
        
        micromamba activate test
        if [[ "${{ inputs.use-vtk }}" == "vtk" ]]; then
          # if [[ ${{ inputs.python-version }} == 3.13 ]]; then
          #   pip install ./cadquery_vtk*.whl
          # else
          #   pip install vtk==${{ env.VTK }}
          # fi
          pip install vtk==${{ env.VTK }}
        fi
        ls -l
        pip install *.whl

        python -c "import OCP; print('Success: OCP', OCP.__version__)"

    # - - -

    - name: Run build123d tests
      shell: bash -l {0}
      run: |
        # Run build123d tests
        set -e
        set -o pipefail

        micromamba activate test

        git clone https://github.com/gumyr/build123d.git

        cd build123d
        git checkout 1af4b0c3129dd152a1c9cb01400c1e648a5de8e2  # pre Gordon face to avoid 7.9. issues
        
        # install ocp_svg and svgelements (a ocp_svg dependency) without cadquery_ocp dependency
        pip install --no-deps ocpsvg svgelements
        
        # Patch to remove dependency ocp_svg, since it relies on cadquery_ocp 7.8
        sed -i.bak '/ocpsvg/d' pyproject.toml
        
        # Patch to allow cadquery_ocp v7.9
        if [[ "${{ inputs.use-vtk }}" == "novtk" ]]; then
          sed -i.bak 's/"cadquery-ocp >= 7\.8, < 7\.9",/"cadquery-ocp-novtk >= 7.9, < 8.0",/' pyproject.toml
        else
          sed -i.bak 's/"cadquery-ocp >= 7\.8, < 7\.9",/"cadquery-ocp >= 7.9, < 8.0",/' pyproject.toml
        fi

        # install build123d without ocp_svg dependency (since it is already installed)
        pip install .

        # 7.9.1. COMPATIBILITY ISSUE
        sed -i.bak '/def test_export_step_timestamp_datetime/i\    @pytest.mark.skip()' tests/test_exporters3d.py
        sed -i.bak '/def test_export_step_timestamp_str/i\    @pytest.mark.skip()' tests/test_exporters3d.py
        # sed -i.bak '/^class ImportSVG(unittest\.TestCase):/a\    __test__ = False' tests/test_importers.py

        if [[ "${{ inputs.use-vtk }}" == "novtk" ]]; then
          pytest tests -v -W ignore \
                 --ignore tests/test_direct_api/test_vtk_poly_data.py \
                 --ignore tests/test_direct_api/test_jupyter.py \
                 --ignore tests/test_examples.py  # 7.9.1. COMPATIBILITY ISSUE
        else
          pytest tests -v -W ignore \
                 --ignore tests/test_examples.py  # 7.9.1. COMPATIBILITY ISSUE
        fi

    # - - -

    - name: Run cadquery tests
      if: inputs.use-vtk == 'vtk'
      shell: bash -l {0}
      run: |
        # Run cadquery tests
        set -e
        set -o pipefail

        git clone https://github.com/cadquery/cadquery.git
        cd cadquery

        # Patch to allow cadquery_ocp v7.9
        sed -i.bak 's/"cadquery-ocp>=7\.8\.1,<7\.9",/"cadquery-ocp>=7.9,< 8.0",/' setup.py

        # if [[ "${{ inputs.python-version }}" == "3.13" ]]; then
        #   patch -p1 < ../patches/cadquery.patch
        # fi

        micromamba activate test

        # 7.9.1. COMPATIBILITY ISSUE
        sed -i.bak '/^from pytest import /s/$/, mark/' tests/test_free_functions.py
        sed -i.bak '/def test_cap/i @mark.skip()' tests/test_free_functions.py
        # workaround for nlopt 2.9.0 not available for Intel Mac
        # if [[ "${{ inputs.os }}" == "macos-13" ]]; then
        #   micromamba install -y nlopt=2.9
        # fi

        # workaround for pypi opt and casadi throwing a seg fault on exit 
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          micromamba install -y nlopt casadi
        fi

        CONDA_PREFIX_BAK=$CONDA_PREFIX
        unset CONDA_PREFIX
        pip install .
        CONDA_PREFIX=$CONDA_PREFIX_BAK

        pytest tests -v -W ignore

    # - - -

    - name: Uninstall test
      # if: inputs.python-version != '3.13'
      shell: bash -l {0}
      run: |
        # Uninstall test
        set -e
        set -o pipefail

        micromamba activate test
        if [[ "${{ inputs.use-vtk }}" == "vtk" ]]; then
           pip uninstall -y cadquery_ocp
        else
          pip uninstall -y cadquery_ocp_novtk
        fi
