name: "Test OCP"
description: "Testing OCP wheels with build123d and CadQuery"
inputs:
  os:
    description: "Operating system to use for the build"
    required: true
  python-version:
    description: "Python version to use for the build"
    required: true
  use-vtk:
    description: "Whether to use VTK in the build"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    
    # - - -

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.5.10"
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        # Create & activate a venv for you
        activate-environment: true

    # - - -

    - name: Install tomli on Python 3.10
      shell: bash -l {0}
      if: ${{ matrix.python-version == '3.10' }}
      run: uv pip install "tomli>=1.1.0"

    # - - -
    
    - name: Download vtk cadquery_ocp wheel
      if: inputs.use-vtk == 'vtk'
      uses: actions/download-artifact@v4
      with:
        name: cadquery-ocp-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}

    # - - -

    - name: Download novtk cadquery_ocp wheel
      if: inputs.use-vtk == 'novtk'
      uses: actions/download-artifact@v4
      with:
        name: cadquery-ocp-novtk-${{ env.WHEEL }}-${{ inputs.os }}-cp${{ inputs.python-version }}

    # - - -

    - name: Install VTK and OCP wheel
      shell: bash -l {0}
      run: |
        # Install VTK and OCP wheel
        set -e
        set -o pipefail
        
        if [[ "${{ inputs.use-vtk }}" == "vtk" ]]; then
          pip install vtk==${{ env.VTK }}
        fi
        ls -l
        uv pip install *.whl

        uv pip list

        uv run python -c "import OCP; print('Success: OCP', OCP.__version__)"

    # - - -

    - name: Run build123d tests
      shell: bash -l {0}
      run: |
        # Run build123d tests
        set -e
        set -o pipefail

        uv pip install packaging

        git clone https://github.com/gumyr/build123d.git
        ocpsvg_min=$(uv run python get-min-version.py build123d/pyproject.toml ocpsvg)
        ocp_gordon_min=$(uv run python get-min-version.py build123d/pyproject.toml ocp_gordon)
        echo "=> ocpsvg $ocpsvg_min / ocp_gordon v$ocp_gordon_min"

        echo "=> Patching and installing ocpsvg"
        git clone https://github.com/snoyer/ocpsvg.git
        cd ocpsvg
        git checkout -b $ocpsvg_min
        # Patch to allow cadquery_ocp v7.9
        if [[ "${{ inputs.use-vtk }}" == "novtk" ]]; then
          sed -i.bak 's/"cadquery-ocp >=.*$/\"cadquery-ocp-novtk >= 7.9, < 8.0\",/' pyproject.toml
        else
          sed -i.bak 's/"cadquery-ocp >=.*$/\"cadquery-ocp >= 7.9, < 8.0\",/' pyproject.toml
        fi
        uv pip install .
        cd ..

        echo "=> Patching and installing ocp_gordon"
        git clone https://github.com/gongfan99/ocp_gordon.git
        cd ocp_gordon
        git checkout -b v$ocp_gordon_min
        # Patch to allow cadquery_ocp v7.9
        if [[ "${{ inputs.use-vtk }}" == "novtk" ]]; then
          sed -i.bak 's/"cadquery-ocp >=.*$/\"cadquery-ocp-novtk >= 7.9, < 8.0\",/' pyproject.toml
        else
          sed -i.bak 's/"cadquery-ocp >=.*$/\"cadquery-ocp >= 7.9, < 8.0\",/' pyproject.toml
        fi
        uv pip install .
        cd ..

        echo "=> Patching and installing build123"
        cd build123d
        # Patch to allow cadquery_ocp v7.9
        if [[ "${{ inputs.use-vtk }}" == "novtk" ]]; then
          sed -i.bak 's/"cadquery-ocp >=.*$/\"cadquery-ocp-novtk >= 7.9, < 8.0\",/' pyproject.toml
        else
          sed -i.bak 's/"cadquery-ocp >=.*$/\"cadquery-ocp >= 7.9, < 8.0\",/' pyproject.toml
        fi
        uv pip install .

        echo "=> Installed packages for test"
        uv pip list

        # 7.9.1. COMPATIBILITY ISSUE
        awk '/def test_export_step_timestamp_datetime/{print "    @pytest.mark.skip()"} 1' tests/test_exporters3d.py > tests/test_exporters3d.py.tmp && mv tests/test_exporters3d.py.tmp tests/test_exporters3d.py
        awk '/def test_export_step_timestamp_str/{print "    @pytest.mark.skip()"} 1' tests/test_exporters3d.py > tests/test_exporters3d.py.tmp && mv tests/test_exporters3d.py.tmp tests/test_exporters3d.py
        # sed -i.bak '/^class ImportSVG(unittest\.TestCase):/a\    __test__ = False' tests/test_importers.py

        if [[ "${{ inputs.use-vtk }}" == "novtk" ]]; then
          echo "=> Running novtk tests"
          uv run --no-sync pytest tests -v -W ignore \
                 --ignore tests/test_direct_api/test_vtk_poly_data.py \
                 --ignore tests/test_direct_api/test_jupyter.py \
                 --ignore tests/test_examples.py  # 7.9.1. COMPATIBILITY ISSUE
        else
          echo "=> Running vtk tests"
          uv run --no-sync pytest tests -v -W ignore \
                 --ignore tests/test_examples.py  # 7.9.1. COMPATIBILITY ISSUE
        fi

    # - - -

    - name: Run cadquery tests
      if: inputs.use-vtk == 'vtk'
      shell: bash -l {0}
      run: |
        # Run cadquery tests
        set -e
        set -o pipefail

        git clone https://github.com/cadquery/cadquery.git
        cd cadquery

        # Patch to allow cadquery_ocp v7.9
        sed -i.bak 's/"cadquery-ocp>=7\.8\.1,<7\.9",/"cadquery-ocp>=7.9,< 8.0",/' setup.py

        uv pip install .

        # 7.9.1. COMPATIBILITY ISSUE
        sed -i.bak '/^from pytest import /s/$/, mark/' tests/test_free_functions.py
        sed -i.bak '/def test_cap/i @mark.skip()' tests/test_free_functions.py
        # workaround for nlopt 2.9.0 not available for Intel Mac
        # if [[ "${{ inputs.os }}" == "macos-13" ]]; then
        #   micromamba install -y nlopt=2.9
        # fi

        # workaround for pypi opt and casadi throwing a seg fault on exit 
        # if [[ "$RUNNER_OS" == "Windows" ]]; then
        #   micromamba install -y nlopt casadi
        # fi

        pytest tests -v -W ignore

    # - - -

    - name: Uninstall test
      # if: inputs.python-version != '3.13'
      shell: bash -l {0}
      run: |
        # Uninstall test
        set -e
        set -o pipefail

        micromamba activate test
        if [[ "${{ inputs.use-vtk }}" == "vtk" ]]; then
           pip uninstall -y cadquery_ocp
        else
          pip uninstall -y cadquery_ocp_novtk
        fi
