name: build-wheel
on:
  workflow_dispatch
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: 3.8
        activate-environment: test
    - name: Build Miniconda environment
      shell: bash --login {0}
      run: |
        sudo apt install -y build-essential libgl1-mesa-dev mesa-common-dev libglu1-mesa-dev libegl1-mesa-dev freeglut3-dev libclang-dev lld
        git clone --recurse-submodules https://github.com/CadQuery/OCP.git
        cd OCP
        conda env create -f env.yml -n ocp
        pip install setuptools
    - name: Run pywrap
      shell: bash --login {0}
      run: |
        conda activate ocp
        cd OCP
        cmake -B new -S . -G Ninja
    - name: Run cmake
      shell: bash --login {0}
      run: |
        conda activate ocp
        cd OCP
        cmake -S OCP -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fuse-ld=lld"
        cmake --build build
    - name: Build Wheel
      shell: bash --login {0}
      run: |
        conda activate ocp
        export LD_LIBRARY_PATH=/home/runner/work/ocp-build-system/ocp-build-system/OCP/build
        python setup.py bdist_wheel
    - name: Find library and Wheel
      shell: bash --login {0}
      run: |
        find /home/runner/work/ocp-build-system -iname *.so
        find /home/runner/work/ocp-build-system -iname *.whl
    - uses: actions/upload-artifact@v2
      with:
        name: OCP-Linux-x86_64
        path: |
          /home/runner/work/ocp-build-system/ocp-build-system/OCP/build/*.so
          /home/runner/work/ocp-build-system/ocp-build-system/dist/*.whl
