name: build-wheel
on:
  workflow_dispatch
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: 3.8
        activate-environment: test
    - name: Build Miniconda environment
      shell: bash --login {0}
      run: |
        sudo apt install -y build-essential libgl1-mesa-dev mesa-common-dev libglu1-mesa-dev freeglut3-dev libclang-dev
        git clone --recurse-submodules https://github.com/CadQuery/OCP.git
        cd OCP
        conda env create -f env.yml -n ocp
        # pip uninstall --yes path.py
        # pip install path
    - name: Run pywrap
      shell: bash --login {0}
      run: |
        conda activate ocp
        cd OCP/pywrap
        python setup.py install
        cd ..
        pywrap all ocp.toml
    - name: Run cmake
      shell: bash --login {0}
      run: |
        conda activate ocp
        cd OCP
        cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -S OCP -B build
        cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON --build build
        # cd /home/runner/work/ocp-build-system/ocp-build-system/OCP/build
        # make VERBOSE=1
    - name: Find library
      shell: bash --login {0}
      run: |
        find /home/runner/work/ocp-build-system -iname *.so
    - uses: actions/upload-artifact@v2
      with:
        name: OCP-Linux-x86_64
        path: /home/runner/work/ocp-build-system/ocp-build-system/OCP/build
