name: Create Python wheel using Conda

on:
  workflow_dispatch
  # push:
  #   branches: [ master ]

env:
  PYTHONUTF8: 1

jobs:
  build:
    name: Build for python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ 'ubuntu', 'macos', 'windows' ]
        python-version: [ '3.8', '3.9', '3.10' ]

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      # See https://cibuildwheel.readthedocs.io/en/stable/
      # Not usable for now, because cadquery libraries require glibc 2.31,
      # but the manylinux images have been created only up to 2.24 (as of 2022-04-11).
      # - name: Build wheels
      #   uses: pypa/cibuildwheel@v2.4.0
      #   with:
      #     output-dir: dist

      # see https://github.com/marketplace/actions/setup-miniconda
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          activate-environment: cadquery-ocp
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Build wheel
        shell: bash -l {0}
        run: |
          conda install -n cadquery-ocp -y ocp=v7.6.3.alpha vtk=9.1.0
          pip install --upgrade pip
          pip install build setuptools wheel requests auditwheel delocate delvewheel
          python -m build --no-isolation

      - name: Print info
        shell: bash -l {0}
        run: |
          conda info
          conda list --explicit
          echo '${{ github.event_name }} ${{ github.ref }}'

      - name: Test wheel
        shell: bash -l {0}
        run: |
          conda deactivate
          conda create --yes -n cadquerytest python=${{ matrix.python-version }}
          conda activate cadquerytest
          pip install dist/*.whl
          python -c "import OCP;print('OCP imported successfully')"

      # see https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cadquery-ocp-${{ matrix.os }}-cp${{ matrix.python-version }}
          path: dist/*.whl
