name: cibuildwheel

#on: [push, pull_request]

on:
  workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] #, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: 3.8
          activate-environment: build

      - name: Setup OCP environment
        run: |
          git clone --recurse-submodules https://github.com/CadQuery/OCP.git
          cd OCP
          conda env create -f env.yml -n ocp
          cd ..
          python -m pip install cibuildwheel==2.3.1
          python -m cibuildwheel --output-dir wheelhouse

      # Used to host cibuildwheel
      # - uses: actions/setup-python@v2
      # - name: Install cibuildwheel
      #   run: |
      #     conda activate ocp
      #     python -m pip install cibuildwheel==2.3.1

      # - name: Build wheels
      #   run: |
      #     conda activate ocp
      #     python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl